# Generated by Django 4.0.5 on 2022-07-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_contacto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='imagen',
        ),
    ]
